# Identificadores obligatorios del proyecto para SonarQube (IE8)
sonar.projectKey=cl.duoc:spring-app-duoc
sonar.projectName=spring-app-duoc
sonar.projectVersion=1.0.0

# Rutas de código fuente y binarios compiled
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Integración obligatoria del reporte de cobertura de JaCoCo (IE7, IE8)
sonar.core.codeCoveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusiones de análisis (ignorar código autogenerado o de configuración)
sonar.exclusions=**/pom.xml, src/test/java/**