spring.application.name=spring-app-duoc
server.port=8080

# OpenAPI / Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Logging
logging.level.root=INFO
logging.level.cl.duoc.springappduoc=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%logger{36}] - %msg%n

management.endpoints.web.exposure.include=health,info,prometheus