apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-microservicio-deployment
  namespace: produccion
  labels:
    app: microservicio-java
spec:
  replicas: 2 # ALTA DISPONIBILIDAD (IE10)
  selector:
    matchLabels:
      app: microservicio-java
  template:
    metadata:
      labels:
        app: microservicio-java
      annotations:
        # INTEGRACIÓN ISTIO (IE12): Inyección automática de Sidecar Proxy para mTLS y métricas
        sidecar.istio.io/inject: "true"
        # INTEGRACIÓN AWS CLOUDWATCH (IE12): Colector integrado para logs de telemetría cloud
        amazoncloudwatch.logs/fluentbit-buffer: "true"
    spec:
      containers:
        - name: microservicio-app
          image: mi-usuario-docker/mi-microservicio-java:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1000m"
              memory: "1024Mi"
            requests:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: java-microservicio-service
  namespace: produccion
spec:
  type: LoadBalancer # Balanceador de Carga
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: microservicio-java
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: java-microservicio-gateway
  namespace: produccion
spec:
  selector:
    istio: ingressgateway # Utiliza el controlador de entrada por defecto de Istio
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*" # Permite peticiones globales enlazadas al balanceador cloud
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: java-microservicio-virtualservice
  namespace: produccion
spec:
  hosts:
    - "*"
  gateways:
    - java-microservicio-gateway
  http:
    - route:
        - destination:
            host: java-microservicio-service.produccion.svc.cluster.local # Enrutamiento DNS interno
            port:
              number: 8080 # Puerto real del contenedor Spring Boot